ci: add GH actions setup
siemens/lint pull request #1
Opened 2024-12-11 13:39 UTC by Killusions

Adds the setup for GitHub actions and releasing. To release start the action manually. Tested here: https://github.com/Killusions/lint

2024-12-11 15:39 UTC, Killusions commented
Finally works now with a lot of configuration (which is sadly all necessary, since semantic release it built for releasing on every push and not committing on release (see [their FAQ](https://semantic-release.gitbook.io/semantic-release/support/faq#making-commits-during-the-release-process-adds-significant-complexity)). semantic-release-monorepo would help for some of our issues, but doesn't work with releasing from dist and would not keep releases of our different packages in sync.

Releases are triggered manually using the "Release" action, the Changelog can not be edited, if a release branch should be used it can be specified before starting the action.

The only caveat is that if we ever rewrite history and leave a tag dangling, semantic release will release on the wrong version (they resolve the version from tags attached to commits on main).

2024-12-11 15:44 UTC, Killusions commented
This needs 2 secrets:

1. NPM_TOKEN
2. REPO_TOKEN (a token from GitHub with write perms on the repo (default CI token doesn't))

2024-12-11 15:50 UTC, Killusions commented
Just tested the [test package published on my namespace](https://www.npmjs.com/package/@killusions/eslint-config-angular) and it works.

2024-12-11 15:57 UTC, kfenner commented
@Killusions Thank you very much 🙏 

@fh1ch Maybe you also want to take a look here. You'd also need to provide the secrets I guess 🙏 🚀

2024-12-17 18:45 UTC, spike-rabbit commented on .github/workflows/build.yml
> +        node-version: [22.x]
I don't think we need the matrix here.

2024-12-17 18:47 UTC, spike-rabbit commented on .github/workflows/build.yml
> +    branches: ['main']
Why restricting to main?

2024-12-17 18:50 UTC, spike-rabbit commented on .github/workflows/build.yml
> +          fetch-depth: 0
Do we really need this? Not exactly sure but please check. Seems for me like gh fetches all commits that are new.

2024-12-17 19:05 UTC, spike-rabbit commented on .github/workflows/release.yml
> +          persist-credentials: false
I understand fetch-depth here, buy why persist-credentials: false?

2024-12-18 10:21 UTC, Killusions commented on .github/workflows/build.yml
> +          fetch-depth: 0
Yes for commitlint, I added it later

2024-12-18 12:23 UTC, timowolf requested changes
We cannot really review and merge unless we

- align on the release and maintenance process with the stakeholders
- document the release process in a markdown file in the repo

2024-12-18 15:29 UTC, Killusions commented on .github/workflows/build.yml
> +        node-version: [22.x]
Removed

2024-12-18 15:29 UTC, Killusions commented on .github/workflows/build.yml
> +    branches: ['main']
Removed

2024-12-18 15:29 UTC, Killusions commented on .github/workflows/release.yml
> +          persist-credentials: false
Removed

2024-12-18 15:29 UTC, Killusions commented
Switched to the default semantic release workflow.

2024-12-18 16:47 UTC, timowolf commented
@Killusions @kfenner @spike-rabbit (cc @fh1ch ) Here is what we should do in the PR

- [ ] We follow the semantic release as close as possible
- [ ] Do not push a commit to main on a release
- [ ] Release on every merge on main
- [ ] Keep version 0.0.0-development in the package.json in the code
- [ ] Replace the 0.0.0-development version number in the NPM releases and also in the archives we can download from GitHub with the real version. The downloaded zip files should contain the correct version number (Something that seems wrong here https://github.com/semantic-release/semantic-release/releases/tag/v24.2.0).  
- [ ] Create a configuration for release candidates on a branch called `next`. Please check if we need to create a next branch for every major release or if we can rebase it on main.
- [ ] Add the NPM and GitHub token to the repo (I can do this )
- [ ] Merge this PR into `next` branch to test if this setup works, by creating 0.1..0-rc{0} release candidates and be able to test this PR end to end. Thus we should verify the npm deployment as well as the release numbers and the commit messages in the changelog
- [ ] Document our process in a markdown file
- [ ] When all good, we merge next in main

Otherwise we cannot test if the PR works. What do you think?

2024-12-18 16:49 UTC, timowolf commented on CHANGELOG.md
I am always looking for a changelog file. Maybe we keep the file and point to the GitHub releases. But we can also add this later.

2024-12-19 13:49 UTC, kfenner commented on CHANGELOG.md
@Killusions For me your changes look good 👍 

@timowolf Agree with everything, maybe the documentation we can do in a follow up when we know all has worked like it should?

2024-12-23 10:30 UTC, timowolf commented
@Killusions Many thanks for the great work. We go ahead with #2  and test it on a next branch first. I am closing this one.

2024-12-23 10:30 UTC, closed without merging